# backend/report_generator.py
import io
import pandas as pd
from fpdf import FPDF
import plotly.io as pio
import logging

def sanitize(text):
    """Sanitizes text to be compatible with FPDF by replacing special characters."""
    if text is None:
        return "N/A"
    return str(text).encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(
    stock_info,
    technical_analysis,
    fundamental_analysis,
    sentiment_analysis,
    news_risk,
    final_score,
    final_verdict
):
    """
    Generates a comprehensive PDF report using consolidated analysis data.
    """
    pdf = FPDF()
    pdf.add_page()

    # --- Header ---
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, f"Stock Analysis Report: {stock_info.get('ticker', 'N/A').upper()}", 0, 1, 'C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, sanitize(stock_info.get('name', '')), 0, 1, 'C')
    pdf.ln(5)

    # --- Final Verdict Section ---
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Final Investment Thesis", 0, 1, 'L')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 8, f"Final Score: {final_score:.2f}/100", 0, 1, 'L')
    pdf.cell(0, 8, f"Verdict: {final_verdict}", 0, 1, 'L')
    pdf.ln(10)

    # --- Analysis Sections (Two-column layout) ---
    col_width = pdf.w / 2 - 15

    # --- Column 1 ---
    # Technical Analysis
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(col_width, 10, 'Technical Analysis', "B", 1, 'L')
    pdf.set_font("Arial", '', 9)
    if "error" in technical_analysis:
        pdf.set_text_color(255, 0, 0)
        pdf.multi_cell(col_width, 5, sanitize(technical_analysis['error']), 0, 'L')
        pdf.set_text_color(0, 0, 0)
    else:
        for key, value in technical_analysis.items():
            if key not in ['verdict', 'period', 'ta_breakdown']: # Exclude non-numeric data for this simple layout
                pdf.cell(col_width - 30, 5, sanitize(key.replace('_', ' ').title()), 0, 0, 'L')
                pdf.cell(30, 5, sanitize(value), 0, 1, 'R')
    pdf.ln(5)

    # News & Sentiment Analysis
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(col_width, 10, 'News & Sentiment', "B", 1, 'L')
    pdf.set_font("Arial", '', 9)
    if "error" in sentiment_analysis:
        pdf.set_text_color(255, 0, 0)
        pdf.multi_cell(col_width, 5, sanitize(sentiment_analysis['error']), 0, 'L')
        pdf.set_text_color(0, 0, 0)
    else:
        pdf.cell(col_width - 30, 5, "Sentiment Score", 0, 0, 'L')
        pdf.cell(30, 5, f"{sentiment_analysis.get('score', 0) * 10:.1f}/100", 0, 1, 'R')
        pdf.cell(col_width - 30, 5, "Sentiment Label", 0, 0, 'L')
        pdf.cell(30, 5, sanitize(sentiment_analysis.get('label')), 0, 1, 'R')
    pdf.ln(5)

    # --- Column 2 ---
    pdf.set_xy(pdf.w / 2, pdf.get_y() - 55) # Reset Y to align with top of column 1

    # Fundamental Analysis
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(col_width, 10, 'Fundamental Analysis', "B", 1, 'L')
    pdf.set_font("Arial", '', 9)
    if "error" in fundamental_analysis:
        pdf.set_text_color(255, 0, 0)
        pdf.multi_cell(col_width, 5, sanitize(fundamental_analysis['error']), 0, 'L')
        pdf.set_text_color(0, 0, 0)
    else:
        # DCF Info
        pdf.cell(col_width - 30, 5, "DCF Upside", 0, 0, 'L')
        pdf.cell(30, 5, sanitize(fundamental_analysis.get("Upside")), 0, 1, 'R')
        # Piotroski
        pdf.cell(col_width - 30, 5, "Piotroski F-Score", 0, 0, 'L')
        pdf.cell(30, 5, sanitize(fundamental_analysis.get("Piotroski F-Score")), 0, 1, 'R')
        # Beneish
        pdf.cell(col_width - 30, 5, "Beneish M-Score", 0, 0, 'L')
        pdf.cell(30, 5, sanitize(fundamental_analysis.get("Beneish M-Score")), 0, 1, 'R')
    pdf.ln(5)

    # --- Footer ---
    pdf.set_y(-15)
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 10, 'Page %s' % pdf.page_no(), 0, 0, 'C')
    pdf.cell(0, 10, 'Generated by StockMatrix - For informational purposes only.', 0, 0, 'R')

    return pdf.output(dest='S').encode('latin-1')

def generate_csv_report(data_list):
    """
    Generates a CSV report from a list of analysis dictionaries.
    """
    if not data_list:
        return ""
    
    # Flatten the dictionaries and create a DataFrame
    flat_data = []
    for entry in data_list:
        # Create a new dictionary to hold the flattened data
        row = {}
        for key, value in entry.items():
            # If the value is a dictionary itself, flatten it
            if isinstance(value, dict):
                for sub_key, sub_value in value.items():
                    row[f"{key}_{sub_key}"] = sub_value
            else:
                row[key] = value
        flat_data.append(row)
        
    df = pd.DataFrame(flat_data)
    
    # Convert DataFrame to CSV string
    csv_buffer = io.StringIO()
    df.to_csv(csv_buffer, index=False)
    return csv_buffer.getvalue().encode('utf-8')