# backend/report_generator.py
import io
import pandas as pd
from fpdf import FPDF
import plotly.graph_objects as go
import logging

def sanitize(text):
    """Sanitizes text to be compatible with FPDF by replacing special characters."""
    if text is None:
        return "N/A"
    return str(text).encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(
    stock_info,
    technical_analysis,
    fundamental_analysis,
    sentiment_analysis,
    news_risk,
    final_score,
    final_verdict,
    historical_data
):
    """
    Generates a comprehensive PDF report with a professional, dynamic layout.
    """
    pdf = FPDF()
    pdf.add_page()

    # --- Header ---
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, f"Stock Analysis Report: {stock_info.get('ticker', 'N/A').upper()}", 0, 1, 'C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, sanitize(stock_info.get('name', '')), 0, 1, 'C')
    pdf.ln(5)

    # --- Final Verdict Section ---
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Final Investment Thesis", 0, 1, 'L')
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 8, f"Final Score: {final_score:.2f}/100", 0, 1, 'L')
    pdf.cell(0, 8, f"Verdict: {final_verdict}", 0, 1, 'L')
    pdf.ln(10)

    # --- Price Chart Section ---
    if historical_data is not None and not historical_data.empty:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, '6-Month Price Trend', "B", 1, 'L')
        
        if 'Date' in historical_data.columns:
            historical_data = historical_data.set_index('Date')

        fig = go.Figure(data=go.Scatter(x=historical_data.index, y=historical_data['Close']))
        fig.update_layout(
            title_text=f"{stock_info.get('ticker', 'N/A')} Price Chart",
            xaxis_title="Date", yaxis_title="Price",
            template="plotly_white", height=300, width=500
        )
        
        img_bytes = fig.to_image(format="png")
        with io.BytesIO(img_bytes) as img_file:
            pdf.image(img_file, x=pdf.w / 4, y=pdf.get_y() + 5, w=pdf.w / 2)
        pdf.ln(60)

    # --- Analysis Sections ---
    col_width = pdf.w / 2 - 15
    
    def draw_section(title, data, is_left_col=True):
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(col_width, 10, title, "B", 1, 'L')
        pdf.set_font("Arial", '', 9)
        
        if "error" in data:
            pdf.set_text_color(255, 0, 0)
            pdf.multi_cell(col_width, 5, sanitize(data['error']), 0, 'L')
            pdf.set_text_color(0, 0, 0)
        else:
            for key, value in data.items():
                pdf.cell(col_width - 30, 5, sanitize(key.replace('_', ' ').title()), 0, 0, 'L')
                pdf.cell(30, 5, sanitize(value), 0, 1, 'R')
        pdf.ln(5)

    # --- Column 1 ---
    y_before_col1 = pdf.get_y()
    draw_section('Technical Analysis', technical_analysis.get('indicators', {}))
    draw_section('News & Sentiment', {
        "Sentiment Score": f"{sentiment_analysis.get('score', 0) * 10:.1f}/100",
        "Sentiment Label": sentiment_analysis.get('label', 'N/A')
    })
    y_after_col1 = pdf.get_y()

    # --- Column 2 ---
    pdf.set_xy(pdf.w / 2, y_before_col1)
    draw_section('Fundamental Analysis', fundamental_analysis.get("Breakdown", {}))
    draw_section('Strategic Perception', {
        "Market Sentiment": f"{sentiment_analysis.get('market_sentiment_score', 0):.1f}/10",
        "Management Quality": f"{sentiment_analysis.get('management_quality_score', 0):.1f}/10"
    })
    y_after_col2 = pdf.get_y()

    # --- Footer ---
    pdf.set_y(max(y_after_col1, y_after_col2) + 10) # Position footer below the longest column
    pdf.set_y(-15)
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 10, 'Page %s' % pdf.page_no(), 0, 0, 'C')
    pdf.cell(0, 10, 'Generated by StockMatrix - For informational purposes only.', 0, 0, 'R')

    return bytes(pdf.output())
