
# config/ticker_lists.py

fallback_tickers = {
    "NSE": [
        "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK", "ITC", "KOTAKBANK", "LT",
        "SBIN", "BHARTIARTL", "ASIANPAINT", "HINDUNILVR", "BAJFINANCE", "WIPRO", "ADANIENT",
        "HCLTECH", "SUNPHARMA", "ONGC", "AXISBANK", "TITAN", "NTPC", "ULTRACEMCO", "POWERGRID",
        "MARUTI", "BAJAJFINSV", "TECHM", "COALINDIA", "GRASIM", "INDUSINDBK", "NESTLEIND",
        "HINDALCO", "JSWSTEEL", "TATASTEEL", "DIVISLAB", "CIPLA", "SBILIFE", "BPCL",
        "HDFCLIFE", "EICHERMOT", "BRITANNIA", "DRREDDY", "HEROMOTOCO", "UPL", "ADANIPORTS",
        "M&M", "TATAMOTORS", "BAJAJ-AUTO", "APOLLOHOSP", "DLF", "SHREECEM"
    ],
    "HKEX": [
        "0001", "0002", "0003", "0005", "0016", "0017", "0027", "0066", "0700", "0762",
        "0836", "0883", "0939", "0941", "0960", "1038", "1088", "1109", "1113", "1299",
        "1928", "1997", "2318", "2388", "2628", "2800", "2823", "2828", "2866", "2888",
        "0293", "3328", "0384", "0388", "3988", "0006", "0823", "0857", "0883", "0939",
        "0941", "0960", "9633", "0968", "0981", "9988", "9999", "0175", "1030", "2319"
    ],
    "NYSE": [
        "JNJ", "V", "JPM", "PG", "UNH", "HD", "MA", "KO", "PFE", "DIS",
        "VZ", "BAC", "MRK", "CVX", "XOM", "WMT", "GS", "C", "T", "MCD",
        "IBM", "NKE", "MO", "PEP", "BMY", "CAT", "AMGN", "NEE", "CL", "AXP",
        "SO", "LMT", "LOW", "D", "GE", "MMM", "DUK", "COP", "EOG", "SPGI",
        "TGT", "USB", "PLD", "RTX", "DE", "CCI", "F", "PSX", "SLB", "BDX"
    ],
    "LSE": [
        "HSBA", "BP", "AZN", "GLEN", "GSK", "ULVR", "BATS", "RIO", "LLOY", "BARC",
        "DGE", "NG", "RKT", "SMIN", "AAL", "STAN", "CNA", "CRH", "SHEL", "AV",
        "BT-A", "PRU", "EXPN", "NXT", "FERG", "MNDI", "IMB", "HLMA", "ENT", "VOD",
        "SPX", "BME", "CPG", "RTO", "BKG", "TW", "TSCO", "UU", "ADM", "SDR",
        "JD", "MKS", "MGGT", "BRBY", "PHNX", "RSA", "III", "STJ", "HIK", "SMT"
    ],
    "TSE": [
        "7203", "6758", "9984", "9432", "8306", "7267", "7974", "6098", "6861", "6501",
        "6902", "8035", "8766", "2914", "9983", "2502", "4502", "3382", "6954", "4021",
        "7751", "6301", "6981", "4568", "6645", "9735", "8031", "2802", "7201", "8604",
        "4911", "2871", "5401", "6869", "5201", "5108", "8801", "1928", "8001", "8802",
        "4507", "3402", "6971", "8267", "6594", "6988", "4704", "5101", "7186", "7731"
    ]
}

# Mapping of all tickers in fallback_tickers to their full company names
TICKER_TO_NAME = {
    # NSE
    "RELIANCE": "Reliance Industries Limited",
    "TCS": "Tata Consultancy Services Limited",
    "INFY": "Infosys Limited",
    "HDFCBANK": "HDFC Bank Limited",
    "ICICIBANK": "ICICI Bank Limited",
    "ITC": "ITC Limited",
    "KOTAKBANK": "Kotak Mahindra Bank Limited",
    "LT": "Larsen & Toubro Limited",
    "SBIN": "State Bank of India",
    "BHARTIARTL": "Bharti Airtel Limited",
    "ASIANPAINT": "Asian Paints Limited",
    "HINDUNILVR": "Hindustan Unilever Limited",
    "BAJFINANCE": "Bajaj Finance Limited",
    "WIPRO": "Wipro Limited",
    "ADANIENT": "Adani Enterprises Limited",
    "HCLTECH": "HCL Technologies Limited",
    "SUNPHARMA": "Sun Pharmaceutical Industries Limited",
    "ONGC": "Oil & Natural Gas Corporation Limited",
    "AXISBANK": "Axis Bank Limited",
    "TITAN": "Titan Company Limited",
    "NTPC": "NTPC Limited",
    "ULTRACEMCO": "UltraTech Cement Limited",
    "POWERGRID": "Power Grid Corporation of India Limited",
    "MARUTI": "Maruti Suzuki India Limited",
    "BAJAJFINSV": "Bajaj Finserv Limited",
    "TECHM": "Tech Mahindra Limited",
    "COALINDIA": "Coal India Limited",
    "GRASIM": "Grasim Industries Limited",
    "INDUSINDBK": "IndusInd Bank Limited",
    "NESTLEIND": "Nestle India Limited",
    "HINDALCO": "Hindalco Industries Limited",
    "JSWSTEEL": "JSW Steel Limited",
    "TATASTEEL": "Tata Steel Limited",
    "DIVISLAB": "Divi's Laboratories Limited",
    "CIPLA": "Cipla Limited",
    "SBILIFE": "SBI Life Insurance Company Limited",
    "BPCL": "Bharat Petroleum Corporation Limited",
    "HDFCLIFE": "HDFC Life Insurance Company Limited",
    "EICHERMOT": "Eicher Motors Limited",
    "BRITANNIA": "Britannia Industries Limited",
    "DRREDDY": "Dr. Reddy's Laboratories Limited",
    "HEROMOTOCO": "Hero MotoCorp Limited",
    "UPL": "UPL Limited",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Limited",
    "M&M": "Mahindra & Mahindra Limited",
    "TATAMOTORS": "Tata Motors Limited",
    "BAJAJ-AUTO": "Bajaj Auto Limited",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Limited",
    "DLF": "DLF Limited",
    "SHREECEM": "Shree Cement Limited",
    # HKEX (examples, not exhaustive)
    "0001": "CK Hutchison Holdings Limited",
    "0002": "CLP Holdings Limited",
    "0003": "Hong Kong & China Gas Company Limited",
    "0005": "HSBC Holdings plc",
    "0016": "Sun Hung Kai Properties Limited",
    "0017": "New World Development Company Limited",
    "0027": "Galaxy Entertainment Group Limited",
    "0066": "MTR Corporation Limited",
    "0700": "Tencent Holdings Limited",
    "0762": "China Unicom (Hong Kong) Limited",
    "0836": "China Resources Power Holdings Company Limited",
    "0883": "CNOOC Limited",
    "0939": "China Construction Bank Corporation",
    "0941": "China Mobile Limited",
    "0960": "Longfor Group Holdings Limited",
    "1038": "CK Infrastructure Holdings Limited",
    "1088": "China Shenhua Energy Company Limited",
    "1109": "China Resources Land Limited",
    "1113": "CK Asset Holdings Limited",
    "1299": "AIA Group Limited",
    "1928": "Sands China Ltd.",
    "1997": "Wharf Real Estate Investment Company Limited",
    "2318": "Ping An Insurance (Group) Company of China, Ltd.",
    "2388": "BOC Hong Kong (Holdings) Limited",
    "2628": "China Life Insurance Company Limited",
    "2800": "Tracker Fund of Hong Kong",
    "2823": "iShares FTSE A50 China Index ETF",
    "2828": "Hang Seng H-Share Index ETF",
    "2866": "China Shipping Development Company Limited",
    "2888": "Standard Chartered PLC",
    "0293": "Cathay Pacific Airways Limited",
    "3328": "Bank of Communications Co., Ltd.",
    "0384": "China Gas Holdings Limited",
    "0388": "Hong Kong Exchanges and Clearing Limited",
    "3988": "Bank of China Limited",
    "0006": "Power Assets Holdings Limited",
    "0823": "Link Real Estate Investment Trust",
    "0857": "PetroChina Company Limited",
    "9633": "Nongfu Spring Co., Ltd.",
    "0968": "Xinyi Solar Holdings Limited",
    "0981": "SMIC Semiconductor Manufacturing International Corporation",
    "9988": "Alibaba Group Holding Limited",
    "9999": "NetEase, Inc.",
    "0175": "Geely Automobile Holdings Limited",
    "1030": "Seazen Group Limited",
    "2319": "Mengniu Dairy Company Limited",
    # NYSE (examples, not exhaustive)
    "JNJ": "Johnson & Johnson",
    "V": "Visa Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "PG": "Procter & Gamble Company",
    "UNH": "UnitedHealth Group Incorporated",
    "HD": "The Home Depot, Inc.",
    "MA": "Mastercard Incorporated",
    "KO": "The Coca-Cola Company",
    "PFE": "Pfizer Inc.",
    "DIS": "The Walt Disney Company",
    "VZ": "Verizon Communications Inc.",
    "BAC": "Bank of America Corporation",
    "MRK": "Merck & Co., Inc.",
    "CVX": "Chevron Corporation",
    "XOM": "Exxon Mobil Corporation",
    "WMT": "Walmart Inc.",
    "GS": "The Goldman Sachs Group, Inc.",
    "C": "Citigroup Inc.",
    "T": "AT&T Inc.",
    "MCD": "McDonald's Corporation",
    "IBM": "International Business Machines Corporation",
    "NKE": "NIKE, Inc.",
    "MO": "Altria Group, Inc.",
    "PEP": "PepsiCo, Inc.",
    "BMY": "Bristol-Myers Squibb Company",
    "CAT": "Caterpillar Inc.",
    "AMGN": "Amgen Inc.",
    "NEE": "NextEra Energy, Inc.",
    "CL": "Colgate-Palmolive Company",
    "AXP": "American Express Company",
    "SO": "The Southern Company",
    "LMT": "Lockheed Martin Corporation",
    "LOW": "Lowe's Companies, Inc.",
    "D": "Dominion Energy, Inc.",
    "GE": "General Electric Company",
    "MMM": "3M Company",
    "DUK": "Duke Energy Corporation",
    "COP": "ConocoPhillips",
    "EOG": "EOG Resources, Inc.",
    "SPGI": "S&P Global Inc.",
    "TGT": "Target Corporation",
    "USB": "U.S. Bancorp",
    "PLD": "Prologis, Inc.",
    "RTX": "RTX Corporation",
    "DE": "Deere & Company",
    "CCI": "Crown Castle Inc.",
    "F": "Ford Motor Company",
    "PSX": "Phillips 66",
    "SLB": "Schlumberger Limited",
    "BDX": "Becton, Dickinson and Company",
    # LSE (examples, not exhaustive)
    "HSBA": "HSBC Holdings plc",
    "BP": "BP p.l.c.",
    "AZN": "AstraZeneca plc",
    "GLEN": "Glencore plc",
    "GSK": "GSK plc",
    "ULVR": "Unilever plc",
    "BATS": "British American Tobacco p.l.c.",
    "RIO": "Rio Tinto Group",
    "LLOY": "Lloyds Banking Group plc",
    "BARC": "Barclays PLC",
    "DGE": "Diageo plc",
    "NG": "National Grid plc",
    "RKT": "Reckitt Benckiser Group plc",
    "SMIN": "Smiths Group plc",
    "AAL": "Anglo American plc",
    "STAN": "Standard Chartered PLC",
    "CNA": "Centrica plc",
    "CRH": "CRH plc",
    "SHEL": "Shell plc",
    "AV": "Aviva plc",
    "BT-A": "BT Group plc",
    "PRU": "Prudential plc",
    "EXPN": "Experian plc",
    "NXT": "Next plc",
    "FERG": "Ferguson plc",
    "MNDI": "Mondi plc",
    "IMB": "Imperial Brands plc",
    "HLMA": "Halma plc",
    "ENT": "Entain plc",
    "VOD": "Vodafone Group plc",
    "SPX": "Spirax-Sarco Engineering plc",
    "BME": "B&M European Value Retail S.A.",
    "CPG": "Compass Group plc",
    "RTO": "Rentokil Initial plc",
    "BKG": "The Berkeley Group Holdings plc",
    "TW": "Taylor Wimpey plc",
    "TSCO": "Tesco plc",
    "UU": "United Utilities Group plc",
    "ADM": "Admiral Group plc",
    "SDR": "Schroders plc",
    "JD": "JD Sports Fashion plc",
    "MKS": "Marks and Spencer Group plc",
    "MGGT": "Meggitt plc",
    "BRBY": "Burberry Group plc",
    "PHNX": "Phoenix Group Holdings plc",
    "RSA": "RSA Insurance Group plc",
    "III": "3i Group plc",
    "STJ": "St. James's Place plc",
    "HIK": "Hikma Pharmaceuticals plc",
    "SMT": "Scottish Mortgage Investment Trust plc",
    # TSE (examples, not exhaustive)
    "7203": "Toyota Motor Corporation",
    "6758": "Sony Group Corporation",
    "9984": "SoftBank Group Corp.",
    "9432": "Nippon Telegraph and Telephone Corporation",
    "8306": "Mitsubishi UFJ Financial Group, Inc.",
    "7267": "Honda Motor Co., Ltd.",
    "7974": "Nintendo Co., Ltd.",
    "6098": "Recruit Holdings Co., Ltd.",
    "6861": "Keyence Corporation",
    "6501": "Hitachi, Ltd.",
    "6902": "Denso Corporation",
    "8035": "Tokyo Electron Limited",
    "8766": "Tokio Marine Holdings, Inc.",
    "2914": "Japan Tobacco Inc.",
    "9983": "Fast Retailing Co., Ltd.",
    "2502": "Asahi Group Holdings, Ltd.",
    "4502": "Takeda Pharmaceutical Company Limited",
    "3382": "Seven & i Holdings Co., Ltd.",
    "6954": "Fanuc Corporation",
    "4021": "Nisshin Seifun Group Inc.",
    "7751": "Canon Inc.",
    "6301": "Komatsu Ltd.",
    "6981": "Murata Manufacturing Co., Ltd.",
    "4568": "Daiichi Sankyo Company, Limited",
    "6645": "OMRON Corporation",
    "9735": "SECOM Co., Ltd.",
    "8031": "Mitsui & Co., Ltd.",
    "2802": "Ajinomoto Co., Inc.",
    "7201": "Nissan Motor Co., Ltd.",
    "8604": "Nomura Holdings, Inc.",
    "4911": "Shiseido Company, Limited",
    "2871": "Nissin Foods Holdings Co., Ltd.",
    "5401": "Nippon Steel Corporation",
    "6869": "Sysmex Corporation",
    "5201": "AGC Inc.",
    "5108": "Bridgestone Corporation",
    "8801": "Mitsui Fudosan Co., Ltd.",
    "1928": "Sekisui House, Ltd.",
    "8001": "Itochu Corporation",
    "8802": "Mitsubishi Estate Co., Ltd.",
    "4507": "Shionogi & Co., Ltd.",
    "3402": "Toray Industries, Inc.",
    "6971": "Kyocera Corporation",
    "8267": "Aeon Co., Ltd.",
    "6594": "Nidec Corporation",
    "6988": "Nitto Denko Corporation",
    "4704": "Trend Micro Incorporated",
    "5101": "The Yokohama Rubber Co., Ltd.",
    "7186": "Concordia Financial Group, Ltd.",
    "7731": "Nikon Corporation",
}
